In [1]:
import pandas as pd
import numpy as np

**DataFrame -- df = pd.DataFrame(data, index, cloumns)**

In [2]:
meusDados = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9; 10, 11, 12')

In [3]:
meusDados

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [4]:
pd.DataFrame(meusDados)

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [5]:
meusDados


matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [6]:
meuDf = pd.DataFrame(meusDados)

In [18]:
print(type(meuDf))

<class 'pandas.core.frame.DataFrame'>


In [9]:
meuDf.dtypes

0    int64
1    int64
2    int64
dtype: object

In [10]:
meuDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       4 non-null      int64
 1   1       4 non-null      int64
 2   2       4 non-null      int64
dtypes: int64(3)
memory usage: 224.0 bytes


In [11]:
meuDf.astype(float)  ## TEM QUE ARMAZENARRRR

0     1     2
0   1.0   2.0   3.0
1   4.0   5.0   6.0
2   7.0   8.0   9.0
3  10.0  11.0  12.0

In [12]:
meuDf = meuDf.astype(float)

meuDf

0     1     2
0   1.0   2.0   3.0
1   4.0   5.0   6.0
2   7.0   8.0   9.0
3  10.0  11.0  12.0

In [13]:
meuDf[1] = meuDf[1].astype(str)

meuDf

0     1     2
0   1.0   2.0   3.0
1   4.0   5.0   6.0
2   7.0   8.0   9.0
3  10.0  11.0  12.0

In [14]:
meuDf.dtypes

0    float64
1     object
2    float64
dtype: object

In [15]:
meuDf.shape  ## mostra quantidade de linhas e quantidade de colunas

(4, 3)

In [22]:
print(meuDf.head) ## função head() mostra as primeiras linhas e colunas da tabela ou df

<bound method NDFrame.head of       0     1     2
0   1.0   2.0   3.0
1   4.0   5.0   6.0
2   7.0   8.0   9.0
3  10.0  11.0  12.0>


In [24]:
meuDf.head()

0     1     2
0   1.0   2.0   3.0
1   4.0   5.0   6.0
2   7.0   8.0   9.0
3  10.0  11.0  12.0

In [19]:
meuDf.head(2)

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0

In [25]:
meuDf.tail()

0     1     2
0   1.0   2.0   3.0
1   4.0   5.0   6.0
2   7.0   8.0   9.0
3  10.0  11.0  12.0

In [26]:
meuDf.tail(2)

0     1     2
2   7.0   8.0   9.0
3  10.0  11.0  12.0

In [27]:
meusDados = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9; 10, 11, 12')
meusDados

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [29]:
meuDf = pd.DataFrame(meusDados)

In [31]:
print(type(meuDf))

<class 'pandas.core.frame.DataFrame'>


In [32]:
meuDf

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [33]:
indice = ['Linha' + str(i) for i in range(4)]

In [34]:
colunas = ['Coluna' + str(i) for i in range(3)]

In [35]:
df2 = pd.DataFrame(data= meusDados, index= indice, columns= colunas)

df2

Coluna0  Coluna1  Coluna2
Linha0        1        2        3
Linha1        4        5        6
Linha2        7        8        9
Linha3       10       11       12

OUUUUU

In [36]:
df2 = pd.DataFrame(meusDados, indice, colunas)

df2

Coluna0  Coluna1  Coluna2
Linha0        1        2        3
Linha1        4        5        6
Linha2        7        8        9
Linha3       10       11       12

**Um dicionário dentro de um dicioário**

In [37]:
df3 = {'Coluna0': {'Linha0': 1, 'Linha1': 4, 'Linha2': 7},
       'Coluna1': {'Linha0': 2, 'Linha1': 5, 'Linha2': 8},
       'Coluna2': {'Linha0': 3, 'Linha1': 6, 'Linha2': 9}
       }
df3

{'Coluna0': {'Linha0': 1, 'Linha1': 4, 'Linha2': 7},
 'Coluna1': {'Linha0': 2, 'Linha1': 5, 'Linha2': 8},
 'Coluna2': {'Linha0': 3, 'Linha1': 6, 'Linha2': 9}}

In [38]:
df3 = pd.DataFrame(df3, indice, colunas)

df3

Coluna0  Coluna1  Coluna2
Linha0      1.0      2.0      3.0
Linha1      4.0      5.0      6.0
Linha2      7.0      8.0      9.0
Linha3      NaN      NaN      NaN

ouuuuu

In [39]:
df3 = pd.DataFrame(df3)

df3

Coluna0  Coluna1  Coluna2
Linha0      1.0      2.0      3.0
Linha1      4.0      5.0      6.0
Linha2      7.0      8.0      9.0
Linha3      NaN      NaN      NaN

In [40]:
df4 = pd.concat([meuDf, df2, df3])

df4

0     1     2  Coluna0  Coluna1  Coluna2
0        1.0   2.0   3.0      NaN      NaN      NaN
1        4.0   5.0   6.0      NaN      NaN      NaN
2        7.0   8.0   9.0      NaN      NaN      NaN
3       10.0  11.0  12.0      NaN      NaN      NaN
Linha0   NaN   NaN   NaN      1.0      2.0      3.0
Linha1   NaN   NaN   NaN      4.0      5.0      6.0
Linha2   NaN   NaN   NaN      7.0      8.0      9.0
Linha3   NaN   NaN   NaN     10.0     11.0     12.0
Linha0   NaN   NaN   NaN      1.0      2.0      3.0
Linha1   NaN   NaN   NaN      4.0      5.0      6.0
Linha2   NaN   NaN   NaN      7.0      8.0      9.0
Linha3   NaN   NaN   NaN      NaN      NaN      NaN

In [41]:
df4.isnull()  # isnull retornar True os valores que são nulos

0      1      2  Coluna0  Coluna1  Coluna2
0       False  False  False     True     True     True
1       False  False  False     True     True     True
2       False  False  False     True     True     True
3       False  False  False     True     True     True
Linha0   True   True   True    False    False    False
Linha1   True   True   True    False    False    False
Linha2   True   True   True    False    False    False
Linha3   True   True   True    False    False    False
Linha0   True   True   True    False    False    False
Linha1   True   True   True    False    False    False
Linha2   True   True   True    False    False    False
Linha3   True   True   True     True     True     True

In [42]:
df4.isnull().sum() ## isnull().sum() -- somar a quantidades dos valores nulos retornados

0          8
1          8
2          8
Coluna0    5
Coluna1    5
Coluna2    5
dtype: int64

In [43]:
df4.isnull().sum().sum() ## total da quantidade dos valores nulos

39

**fillna: leia como um "filtrar Not A Number" - para filtrar os valores Not a Number**

In [45]:
print(df4.fillna) ##fillna -- filtra os valores not a number

<bound method NDFrame.fillna of            0     1     2  Coluna0  Coluna1  Coluna2
0        1.0   2.0   3.0      NaN      NaN      NaN
1        4.0   5.0   6.0      NaN      NaN      NaN
2        7.0   8.0   9.0      NaN      NaN      NaN
3       10.0  11.0  12.0      NaN      NaN      NaN
Linha0   NaN   NaN   NaN      1.0      2.0      3.0
Linha1   NaN   NaN   NaN      4.0      5.0      6.0
Linha2   NaN   NaN   NaN      7.0      8.0      9.0
Linha3   NaN   NaN   NaN     10.0     11.0     12.0
Linha0   NaN   NaN   NaN      1.0      2.0      3.0
Linha1   NaN   NaN   NaN      4.0      5.0      6.0
Linha2   NaN   NaN   NaN      7.0      8.0      9.0
Linha3   NaN   NaN   NaN      NaN      NaN      NaN>


In [46]:
df5 = df4.fillna(df4.mean())

df5

0     1     2    Coluna0    Coluna1    Coluna2
0        1.0   2.0   3.0   4.857143   5.857143   6.857143
1        4.0   5.0   6.0   4.857143   5.857143   6.857143
2        7.0   8.0   9.0   4.857143   5.857143   6.857143
3       10.0  11.0  12.0   4.857143   5.857143   6.857143
Linha0   5.5   6.5   7.5   1.000000   2.000000   3.000000
Linha1   5.5   6.5   7.5   4.000000   5.000000   6.000000
Linha2   5.5   6.5   7.5   7.000000   8.000000   9.000000
Linha3   5.5   6.5   7.5  10.000000  11.000000  12.000000
Linha0   5.5   6.5   7.5   1.000000   2.000000   3.000000
Linha1   5.5   6.5   7.5   4.000000   5.000000   6.000000
Linha2   5.5   6.5   7.5   7.000000   8.000000   9.000000
Linha3   5.5   6.5   7.5   4.857143   5.857143   6.857143

**dropna - vaii deletar faça a copia - linha inteira**

In [47]:
df8 = df5.copy()

In [48]:
df4.dropna(inplace = True)

df4

Empty DataFrame
Columns: [0, 1, 2, Coluna0, Coluna1, Coluna2]
Index: []

In [49]:
df5

0     1     2    Coluna0    Coluna1    Coluna2
0        1.0   2.0   3.0   4.857143   5.857143   6.857143
1        4.0   5.0   6.0   4.857143   5.857143   6.857143
2        7.0   8.0   9.0   4.857143   5.857143   6.857143
3       10.0  11.0  12.0   4.857143   5.857143   6.857143
Linha0   5.5   6.5   7.5   1.000000   2.000000   3.000000
Linha1   5.5   6.5   7.5   4.000000   5.000000   6.000000
Linha2   5.5   6.5   7.5   7.000000   8.000000   9.000000
Linha3   5.5   6.5   7.5  10.000000  11.000000  12.000000
Linha0   5.5   6.5   7.5   1.000000   2.000000   3.000000
Linha1   5.5   6.5   7.5   4.000000   5.000000   6.000000
Linha2   5.5   6.5   7.5   7.000000   8.000000   9.000000
Linha3   5.5   6.5   7.5   4.857143   5.857143   6.857143

In [50]:
df5.dropna(subset = [1], inplace = True)

df5

0     1     2    Coluna0    Coluna1    Coluna2
0        1.0   2.0   3.0   4.857143   5.857143   6.857143
1        4.0   5.0   6.0   4.857143   5.857143   6.857143
2        7.0   8.0   9.0   4.857143   5.857143   6.857143
3       10.0  11.0  12.0   4.857143   5.857143   6.857143
Linha0   5.5   6.5   7.5   1.000000   2.000000   3.000000
Linha1   5.5   6.5   7.5   4.000000   5.000000   6.000000
Linha2   5.5   6.5   7.5   7.000000   8.000000   9.000000
Linha3   5.5   6.5   7.5  10.000000  11.000000  12.000000
Linha0   5.5   6.5   7.5   1.000000   2.000000   3.000000
Linha1   5.5   6.5   7.5   4.000000   5.000000   6.000000
Linha2   5.5   6.5   7.5   7.000000   8.000000   9.000000
Linha3   5.5   6.5   7.5   4.857143   5.857143   6.857143

**Drop - deletando colunas inteiras**

In [51]:
df6 = df5.drop(columns = ['Coluna0'])

df6

0     1     2    Coluna1    Coluna2
0        1.0   2.0   3.0   5.857143   6.857143
1        4.0   5.0   6.0   5.857143   6.857143
2        7.0   8.0   9.0   5.857143   6.857143
3       10.0  11.0  12.0   5.857143   6.857143
Linha0   5.5   6.5   7.5   2.000000   3.000000
Linha1   5.5   6.5   7.5   5.000000   6.000000
Linha2   5.5   6.5   7.5   8.000000   9.000000
Linha3   5.5   6.5   7.5  11.000000  12.000000
Linha0   5.5   6.5   7.5   2.000000   3.000000
Linha1   5.5   6.5   7.5   5.000000   6.000000
Linha2   5.5   6.5   7.5   8.000000   9.000000
Linha3   5.5   6.5   7.5   5.857143   6.857143

In [52]:
df7 = df6.drop(index = [2])

df7

0     1     2    Coluna1    Coluna2
0        1.0   2.0   3.0   5.857143   6.857143
1        4.0   5.0   6.0   5.857143   6.857143
3       10.0  11.0  12.0   5.857143   6.857143
Linha0   5.5   6.5   7.5   2.000000   3.000000
Linha1   5.5   6.5   7.5   5.000000   6.000000
Linha2   5.5   6.5   7.5   8.000000   9.000000
Linha3   5.5   6.5   7.5  11.000000  12.000000
Linha0   5.5   6.5   7.5   2.000000   3.000000
Linha1   5.5   6.5   7.5   5.000000   6.000000
Linha2   5.5   6.5   7.5   8.000000   9.000000
Linha3   5.5   6.5   7.5   5.857143   6.857143

**Valores únicos**

In [53]:
df5.Coluna2.unique()

array([ 6.85714286,  3.        ,  6.        ,  9.        , 12.        ])

In [54]:
df5.columns.unique()

Index([0, 1, 2, 'Coluna0', 'Coluna1', 'Coluna2'], dtype='object')

In [55]:
df5.index.unique()

Index([0, 1, 2, 3, 'Linha0', 'Linha1', 'Linha2', 'Linha3'], dtype='object')

**Sort_values - para ordenar os dados**

In [56]:
df8.sort_values(by = 'Coluna1')

0     1     2    Coluna0    Coluna1    Coluna2
Linha0   5.5   6.5   7.5   1.000000   2.000000   3.000000
Linha0   5.5   6.5   7.5   1.000000   2.000000   3.000000
Linha1   5.5   6.5   7.5   4.000000   5.000000   6.000000
Linha1   5.5   6.5   7.5   4.000000   5.000000   6.000000
0        1.0   2.0   3.0   4.857143   5.857143   6.857143
1        4.0   5.0   6.0   4.857143   5.857143   6.857143
2        7.0   8.0   9.0   4.857143   5.857143   6.857143
3       10.0  11.0  12.0   4.857143   5.857143   6.857143
Linha3   5.5   6.5   7.5   4.857143   5.857143   6.857143
Linha2   5.5   6.5   7.5   7.000000   8.000000   9.000000
Linha2   5.5   6.5   7.5   7.000000   8.000000   9.000000
Linha3   5.5   6.5   7.5  10.000000  11.000000  12.000000

**df.rename() - renomerar**

In [59]:
df8.rename(columns = {'Coluna1':'COLUNA1'}, inplace = True)

df8

0  Fevereiro     2    Coluna0    COLUNA1    Coluna2
0        1.0        2.0   3.0   4.857143   5.857143   6.857143
1        4.0        5.0   6.0   4.857143   5.857143   6.857143
2        7.0        8.0   9.0   4.857143   5.857143   6.857143
3       10.0       11.0  12.0   4.857143   5.857143   6.857143
Linha0   5.5        6.5   7.5   1.000000   2.000000   3.000000
Linha1   5.5        6.5   7.5   4.000000   5.000000   6.000000
Linha2   5.5        6.5   7.5   7.000000   8.000000   9.000000
Linha3   5.5        6.5   7.5  10.000000  11.000000  12.000000
Linha0   5.5        6.5   7.5   1.000000   2.000000   3.000000
Linha1   5.5        6.5   7.5   4.000000   5.000000   6.000000
Linha2   5.5        6.5   7.5   7.000000   8.000000   9.000000
Linha3   5.5        6.5   7.5   4.857143   5.857143   6.857143

In [60]:
df8.rename(columns = {0:'Janeiro', 1:'Fevereiro', 2:'Março', 'Coluna0':'Abril',
                      'Coluna1':'Maio', 'Coluna2':'Junho', 'Coluna0':'Julho',
                      'COLUNA1':'Agosto', 'Coluna2':'Setembro'}, inplace = True)
df8

Janeiro  Fevereiro  Março      Julho     Agosto   Setembro
0           1.0        2.0    3.0   4.857143   5.857143   6.857143
1           4.0        5.0    6.0   4.857143   5.857143   6.857143
2           7.0        8.0    9.0   4.857143   5.857143   6.857143
3          10.0       11.0   12.0   4.857143   5.857143   6.857143
Linha0      5.5        6.5    7.5   1.000000   2.000000   3.000000
Linha1      5.5        6.5    7.5   4.000000   5.000000   6.000000
Linha2      5.5        6.5    7.5   7.000000   8.000000   9.000000
Linha3      5.5        6.5    7.5  10.000000  11.000000  12.000000
Linha0      5.5        6.5    7.5   1.000000   2.000000   3.000000
Linha1      5.5        6.5    7.5   4.000000   5.000000   6.000000
Linha2      5.5        6.5    7.5   7.000000   8.000000   9.000000
Linha3      5.5        6.5    7.5   4.857143   5.857143   6.857143

In [61]:
df8.rename(columns = { 1: 'Fevereiro'}, inplace = True)

df8

Janeiro  Fevereiro  Março      Julho     Agosto   Setembro
0           1.0        2.0    3.0   4.857143   5.857143   6.857143
1           4.0        5.0    6.0   4.857143   5.857143   6.857143
2           7.0        8.0    9.0   4.857143   5.857143   6.857143
3          10.0       11.0   12.0   4.857143   5.857143   6.857143
Linha0      5.5        6.5    7.5   1.000000   2.000000   3.000000
Linha1      5.5        6.5    7.5   4.000000   5.000000   6.000000
Linha2      5.5        6.5    7.5   7.000000   8.000000   9.000000
Linha3      5.5        6.5    7.5  10.000000  11.000000  12.000000
Linha0      5.5        6.5    7.5   1.000000   2.000000   3.000000
Linha1      5.5        6.5    7.5   4.000000   5.000000   6.000000
Linha2      5.5        6.5    7.5   7.000000   8.000000   9.000000
Linha3      5.5        6.5    7.5   4.857143   5.857143   6.857143

In [62]:
df9 = df8.rename(index = {0: 'Elon Musk', 1:'Bill Gates', 2:'Bernard Arnault', 3:'Mark Zuckerberg'})

df9

Janeiro  Fevereiro  Março      Julho     Agosto   Setembro
Elon Musk            1.0        2.0    3.0   4.857143   5.857143   6.857143
Bill Gates           4.0        5.0    6.0   4.857143   5.857143   6.857143
Bernard Arnault      7.0        8.0    9.0   4.857143   5.857143   6.857143
Mark Zuckerberg     10.0       11.0   12.0   4.857143   5.857143   6.857143
Linha0               5.5        6.5    7.5   1.000000   2.000000   3.000000
Linha1               5.5        6.5    7.5   4.000000   5.000000   6.000000
Linha2               5.5        6.5    7.5   7.000000   8.000000   9.000000
Linha3               5.5        6.5    7.5  10.000000  11.000000  12.000000
Linha0               5.5        6.5    7.5   1.000000   2.000000   3.000000
Linha1               5.5        6.5    7.5   4.000000   5.000000   6.000000
Linha2               5.5        6.5    7.5   7.000000   8.000000   9.000000
Linha3               5.5        6.5    7.5   4.857143   5.857143   6.857143

In [63]:
df8.reset_index()

index  Janeiro  Fevereiro  Março      Julho     Agosto   Setembro
0        0      1.0        2.0    3.0   4.857143   5.857143   6.857143
1        1      4.0        5.0    6.0   4.857143   5.857143   6.857143
2        2      7.0        8.0    9.0   4.857143   5.857143   6.857143
3        3     10.0       11.0   12.0   4.857143   5.857143   6.857143
4   Linha0      5.5        6.5    7.5   1.000000   2.000000   3.000000
5   Linha1      5.5        6.5    7.5   4.000000   5.000000   6.000000
6   Linha2      5.5        6.5    7.5   7.000000   8.000000   9.000000
7   Linha3      5.5        6.5    7.5  10.000000  11.000000  12.000000
8   Linha0      5.5        6.5    7.5   1.000000   2.000000   3.000000
9   Linha1      5.5        6.5    7.5   4.000000   5.000000   6.000000
10  Linha2      5.5        6.5    7.5   7.000000   8.000000   9.000000
11  Linha3      5.5        6.5    7.5   4.857143   5.857143   6.857143

In [64]:
df8.value_counts('Março')

Março
7.5     8
3.0     1
6.0     1
9.0     1
12.0    1
Name: count, dtype: int64

In [65]:
df8.columns.value_counts().sum()

6

In [66]:
df8.index.value_counts().sum()

12